export const Constants = {
  CURRENT_LOCK_VERSION: 1,
  LOCK_FILE_NAME: 'integrate-lock.json',
  UPGRADE_FOLDER_NAME: '.upgrade',
  UPGRADE_CONFIG_FILE_NAME: 'upgrade.yml',
  GIT_FOLDER_NAME: '.git',
  PACKAGE_JSON_FILE_NAME: 'package.json',
  APP_DELEGATE_FILE_NAME: 'AppDelegate.mm',
  NOTIFICATION_SERVICE_FILE_NAME: 'NotificationService.m',
  NOTIFICATION_VIEW_CONTROLLER_FILE_NAME: 'NotificationViewController.m',
  PLIST_FILE_NAME: 'Info.plist',
  ANDROID_MAIN_FILE_PATH: 'android/app/src/main',
  ANDROID_MANIFEST_FILE_NAME: 'AndroidManifest.xml',
  STRINGS_XML_FILE_NAME: 'strings.xml',
  BUILD_GRADLE_FILE_NAME: 'build.gradle',
  SETTINGS_GRADLE_FILE_NAME: 'settings.gradle',
  MAIN_APPLICATION_JAVA_FILE_NAME: 'MainApplication.java',
  MAIN_APPLICATION_KT_FILE_NAME: 'MainApplication.kt',
  MAIN_ACTIVITY_JAVA_FILE_NAME: 'MainActivity.java',
  MAIN_ACTIVITY_KT_FILE_NAME: 'MainActivity.kt',
  POD_FILE_NAME: 'Podfile',
  GITIGNORE_FILE_NAME: '.gitignore',
  XCODEPROJ_EXT: '.xcodeproj',
  CONFIG_FILE_NAME: 'integrate.yml',
  XCODE_APPLICATION_TYPE: 'com.apple.product-type.application',
  XCConfig_FILE_NAME: 'Config.xcconfig',
  REMOTE_CONFIG_REPO:
    'https://raw.githubusercontent.com/react-native-integrate/configs/main/packages/[package]/integrate.yml',
  REMOTE_REPO:
    'https://raw.githubusercontent.com/react-native-integrate/configs/main/packages/[package]/',
  REMOTE_CONFIG_REPO_HOME:
    'https://github.com/react-native-integrate/configs/tree/main/packages/[package]/integrate.yml',
};
